import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};

// Bảng dịch Việt - Anh
const translations = {
    vi: {
        // Header
        'search_placeholder': 'Tìm kiếm sản phẩm...',
        'cart': 'Giỏ hàng',
        'login': 'Đăng nhập',
        'register': 'Đăng ký',
        'logout': 'Đăng xuất',
        'profile': 'Tài khoản',
        'admin': 'Quản trị',
        'wishlist': 'Yêu thích',
        'compare': 'So sánh',
        'notifications': 'Thông báo',

        // Homepage
        'flash_sale': 'Flash Sale',
        'top_search': 'Tìm kiếm hàng đầu',
        'categories': 'Danh mục',
        'suggestions': 'Gợi ý hôm nay',
        'view_all': 'Xem tất cả',
        'buy_now': 'Mua ngay',
        'add_to_cart': 'Thêm vào giỏ',
        'sold': 'Đã bán',

        // Product
        'product_detail': 'Chi tiết sản phẩm',
        'description': 'Mô tả',
        'reviews': 'Đánh giá',
        'size_guide': 'Hướng dẫn chọn size',
        'similar_products': 'Sản phẩm tương tự',
        'you_may_like': 'Có thể bạn sẽ thích',
        'write_review': 'Viết đánh giá',
        'rating': 'Đánh giá',
        'comment': 'Nhận xét',
        'submit_review': 'Gửi đánh giá',

        // Cart & Checkout
        'your_cart': 'Giỏ hàng của bạn',
        'checkout': 'Thanh toán',
        'total': 'Tổng cộng',
        'shipping_info': 'Thông tin giao hàng',
        'payment_method': 'Phương thức thanh toán',
        'cod': 'Thanh toán khi nhận hàng',
        'bank_transfer': 'Chuyển khoản ngân hàng',
        'e_wallet': 'Ví điện tử',
        'place_order': 'Đặt hàng',
        'order_success': 'Đặt hàng thành công!',
        'discount_code': 'Mã giảm giá',
        'apply': 'Áp dụng',

        // Orders
        'my_orders': 'Đơn hàng của tôi',
        'order_tracking': 'Theo dõi đơn hàng',
        'processing': 'Đang xử lý',
        'shipping': 'Đang giao',
        'delivered': 'Đã giao',
        'cancelled': 'Đã hủy',
        'cancel_order': 'Hủy đơn hàng',
        'order_detail': 'Chi tiết đơn hàng',

        // Profile
        'my_profile': 'Thông tin cá nhân',
        'full_name': 'Họ và tên',
        'phone': 'Số điện thoại',
        'address': 'Địa chỉ',
        'city': 'Tỉnh/Thành phố',
        'district': 'Quận/Huyện',
        'ward': 'Phường/Xã',
        'save': 'Lưu',
        'edit': 'Sửa',

        // Chat
        'chat_support': 'Hỗ trợ trực tuyến',
        'chat_greeting': 'Xin chào! Tôi có thể giúp gì cho bạn?',
        'type_message': 'Nhập tin nhắn...',
        'send': 'Gửi',

        // Virtual Try-On
        'virtual_tryon': 'Thử đồ 3D',
        'height': 'Chiều cao',
        'weight': 'Cân nặng',
        'fit_score': 'Độ phù hợp',

        // Footer
        'newsletter': 'Đăng ký nhận tin',
        'newsletter_desc': 'Đăng ký để nhận mã giảm giá và ưu đãi mới nhất',
        'subscribe': 'Đăng ký',
        'about_us': 'Về chúng tôi',
        'help_center': 'Trung tâm trợ giúp',
        'policies': 'Chính sách',

        // General
        'loading': 'Đang tải...',
        'error': 'Có lỗi xảy ra',
        'success': 'Thành công',
        'confirm': 'Xác nhận',
        'cancel': 'Hủy',
        'close': 'Đóng',
        'back': 'Quay lại',
        'no_results': 'Không tìm thấy kết quả',
        'language': 'Ngôn ngữ',
        'search_btn': 'Tìm kiếm',
        'customer_service': 'Chăm sóc khách hàng',
        'about_shopee': 'Về VFit',
        'connect_with_us': 'Kết nối với chúng tôi:',
        'payment_methods_label': 'Phương thức thanh toán:',
        'copyright': 'Bản quyền thuộc về VFit.',
        'country_region': 'Quốc gia & Khu vực:',
        'footer_desc': 'Nền tảng thương mại điện tử hàng đầu Việt Nam, mang đến trải nghiệm mua sắm tuyệt vời với hàng triệu sản phẩm chất lượng.',
        'help_center_link': 'Trung tâm trợ giúp',
        'buy_guide': 'Hướng dẫn mua hàng',
        'sell_guide': 'Hướng dẫn bán hàng',
        'payment_link': 'Thanh toán',
        'shipping_link': 'Vận chuyển',
        'return_policy': 'Chính sách đổi trả',
        'intro_shopee': 'Giới thiệu VFit',
        'terms': 'Điều khoản',
        'privacy_policy': 'Chính sách bảo mật',
        'cookie_policy': 'Chính sách cookie',

        // FlashSale
        'ends_in': 'Kết thúc sau:',
        'view_all_flash': 'Xem Tất Cả Flash Sale',
        'in_stock': 'Còn',

        // Category
        'fashion_categories': 'DANH MỤC THỜI TRANG',

        // ProductList
        'no_products': 'Không có sản phẩm nào',
        'remove_wishlist': 'Bỏ yêu thích',
        'add_wishlist': 'Thêm vào yêu thích',
        'quick_view': 'Xem nhanh',
        'view_product': 'Xem sản phẩm',

        // CartModal
        'empty_cart': 'Chưa có sản phẩm nào trong giỏ.',
        'select_all': 'Chọn tất cả',
        'quantity_label': 'Số lượng:',
        'delete': 'Xóa',
        'total_payment': 'Tổng thanh toán',
        'buy_items': 'Mua Hàng',
        'select_item_warning': 'Vui lòng chọn ít nhất một sản phẩm để mua hàng!',
        'products_unit': 'sản phẩm',

        // ProductDetail
        'color_label': 'Màu Sắc',
        'size_label': 'Kích thước (Size)',
        'add_to_cart_btn': 'Thêm Vào Giỏ',
        'buy_now_btn': 'Mua Ngay',
        'try_3d_btn': 'Thử lên người mẫu 3D',
        'product_specs': 'CHI TIẾT SẢN PHẨM',
        'category_label': 'Danh Mục',
        'material_label': 'Chất liệu',
        'material_value': 'Denim, Cotton cao cấp',
        'pattern_label': 'Mẫu',
        'pattern_value': 'Trơn / Họa tiết',
        'origin_label': 'Xuất xứ',
        'origin_value': 'Việt Nam',
        'product_reviews_title': 'ĐÁNH GIÁ SẢN PHẨM',
        'review_count_label': 'đánh giá',
        'all_filter': 'Tất Cả',
        'star_label': 'Sao',
        'has_comments': 'Có Bình Luận',
        'has_images': 'Có Hình Ảnh',
        'write_your_review': 'Viết Đánh Giá Của Bạn',
        'your_rating': 'Đánh giá của bạn',
        'your_comment': 'Nhận xét của bạn',
        'share_experience': 'Chia sẻ trải nghiệm của bạn về sản phẩm này...',
        'submit_review_btn': 'Gửi Đánh Giá',
        'login_to_review': 'Bạn cần đăng nhập để đánh giá',
        'login_to_review_desc': 'Vui lòng đăng nhập để chia sẻ trải nghiệm của bạn về sản phẩm này',
        'login_now': 'Đăng Nhập Ngay',
        'no_matching_reviews': 'Chưa có đánh giá nào phù hợp với bộ lọc',
        'view_more_reviews': 'Xem Thêm Đánh Giá',
        'classification': 'Phân loại:',
        'shop_reply': 'Phản Hồi Của Shop:',
        'product_not_found': 'Không tìm thấy sản phẩm',
        'please_login_review': 'Vui lòng đăng nhập để đánh giá sản phẩm',
        'please_enter_review': 'Vui lòng nhập nội dung đánh giá',
        'review_submitted': 'Đánh giá của bạn đã được gửi thành công!',
        'need_login_buy': 'Bạn cần đăng nhập để mua hàng!',
        'please_select_size': 'Vui lòng chọn Size!',
        'fashion_breadcrumb': 'Thời Trang',
        'not_selected': 'Chưa chọn',
        'user_default': 'Người dùng',

        // Checkout
        'standard_shipping': 'Giao hàng tiêu chuẩn',
        'express_shipping': 'Giao hàng nhanh',
        'super_shipping': 'Giao hàng siêu tốc',
        'standard_time': '3-5 ngày',
        'express_time': '1-2 ngày',
        'super_time': 'Trong ngày',
        'today_text': 'Hôm nay',
        'selected_products': 'Sản phẩm đã chọn',
        'product_col': 'Sản Phẩm',
        'unit_price': 'Đơn Giá',
        'quantity_col': 'Số Lượng',
        'total_col': 'Tổng',
        'shipping_method_label': 'Phương thức vận chuyển',
        'shipping_hint': 'Chọn phương thức giao hàng phù hợp với bạn',
        'expected_label': 'Dự kiến',
        'payment_title': 'Thanh toán',
        'subtotal': 'Tạm tính:',
        'shipping_fee_label': 'Phí vận chuyển:',
        'expected_delivery': 'Giao dự kiến:',
        'discount_code_label': 'Mã giảm giá',
        'enter_discount': 'Nhập mã giảm giá',
        'receiver_info': 'Thông tin nhận hàng',
        'full_name_star': 'Họ và tên *',
        'phone_star': 'Số điện thoại *',
        'address_star': 'Địa chỉ *',
        'address_hint': 'Để thay đổi địa chỉ, vui lòng cập nhật trong',
        'your_profile_link': 'Hồ sơ của bạn',
        'ward_star': 'Phường/Xã *',
        'district_star': 'Quận/Huyện *',
        'city_star': 'Tỉnh/Thành phố *',
        'cod_full': 'Thanh toán khi nhận hàng (COD)',
        'banking_full': 'Chuyển khoản ngân hàng',
        'online_full': 'Thanh toán online (MoMo, ZaloPay, VNPAY...)',
        'security_title': 'Bảo mật thông tin:',
        'security_desc': 'Thông tin của bạn được mã hóa và bảo mật tuyệt đối. Chúng tôi cam kết không chia sẻ dữ liệu cá nhân với bên thứ ba.',
        'processing_order': 'Đang xử lý...',
        'place_order_now': 'Đặt hàng ngay',
        'confirm_order_title': 'Xác nhận đơn hàng',
        'confirm_check_info': 'Vui lòng kiểm tra lại thông tin đơn hàng của bạn:',
        'confirm_order_btn': 'Xác nhận đặt hàng',
        'cart_step': '1. Giỏ hàng',
        'shipping_step': '2. Vận chuyển',
        'payment_step': '3. Thanh toán',
        'no_products_selected': 'Chưa có sản phẩm nào được chọn',
        'select_products_hint': 'Vui lòng chọn sản phẩm để thanh toán!',
        'select_products_btn': 'CHỌN SẢN PHẨM',
        'no_product_found': 'Không tìm thấy sản phẩm!',
        'please_select_products': 'Vui lòng chọn sản phẩm trước!',
        'please_login_checkout': 'Vui lòng đăng nhập để thanh toán!',
        'update_address_warning': 'Vui lòng cập nhật địa chỉ giao hàng trong Hồ sơ của bạn!',
        'update_full_info': 'Vui lòng cập nhật đầy đủ thông tin giao hàng trong Hồ sơ!',
        'no_products_warning': 'Không có sản phẩm nào được chọn!',
        'please_login_again': 'Vui lòng đăng nhập lại!',
        'order_failed': 'Đặt hàng thất bại!',
        'used_all_coupons': 'Bạn đã sử dụng hết mã giảm giá',
        'coupon_from_newsletter': 'Mã từ đăng ký nhận tin',
        'discount_code_text': 'Mã giảm giá',
        'select_btn': 'Chọn',
        'hide_btn': 'Ẩn',
        'codes_count': 'mã',
        'enter_discount_error': 'Vui lòng nhập mã giảm giá',
        'coupon_invalid': 'Mã giảm giá không hợp lệ',
        'please_login_coupon': 'Vui lòng đăng nhập để sử dụng mã giảm giá',
        'cannot_check_coupon': 'Không thể kiểm tra mã giảm giá. Vui lòng thử lại',
        'coupon_already_used': 'Bạn đã sử dụng mã giảm giá này rồi',
        'coupon_check_error': 'Lỗi kiểm tra mã giảm giá. Vui lòng thử lại',

        // UserProfile
        'personal_info': 'Thông tin cá nhân',
        'my_orders_tab': 'Đơn hàng của tôi',
        'select_city': '-- Chọn Tỉnh/Thành phố --',
        'select_district': '-- Chọn Quận/Huyện --',
        'select_ward': '-- Chọn Phường/Xã --',
        'street_address': 'Số nhà, tên đường',
        'street_placeholder': 'Ví dụ: Số 123, Đường Nguyễn Văn A',
        'view_on_map': 'Xem vị trí trên bản đồ',
        'save_info': 'Lưu thông tin',
        'loading_orders': 'Đang tải đơn hàng...',
        'no_orders_yet': 'Bạn chưa có đơn hàng nào',
        'shop_now': 'Mua sắm ngay',
        'order_label': 'Đơn hàng:',
        'total_amount_label': 'Tổng tiền:',
        'shipping_info_title': 'Thông tin giao hàng',
        'reorder_btn': 'Đặt lại',
        'delete_order_btn': 'Xóa đơn hàng',
        'confirm_cancel': 'Bạn có chắc chắn muốn hủy đơn hàng này?',
        'confirm_delete': 'Bạn có chắc chắn muốn xóa đơn hàng này?',
        'cancel_success': 'Đã hủy đơn hàng thành công',
        'delete_success': 'Đã xóa đơn hàng thành công',
        'added_to_cart_msg': 'Đã thêm sản phẩm vào giỏ hàng!',
        'cannot_load_orders': 'Không thể tải đơn hàng',
        'please_login_page': 'Vui lòng đăng nhập để xem trang này!',

        // TopSearch
        'top_search_title': 'TÌM KIẾM HÀNG ĐẦU',
        'sold_count_monthly': 'Đã bán',
        'monthly_suffix': '/ tháng',

        // ReviewCarousel
        'customer_reviews_title': '💬 Khách Hàng Nói Gì Về Chúng Tôi',
        'customer_reviews_subtitle': 'Hơn 100,000+ khách hàng hài lòng',
        'review_product_label': 'Sản phẩm:',

        // BrandPartners
        'brand_partners_title': '🤝 Đối Tác Thương Hiệu',
        'brand_partners_subtitle': 'Hợp tác với các thương hiệu hàng đầu thế giới',
    },
    en: {
        // Header
        'search_placeholder': 'Search products...',
        'cart': 'Cart',
        'login': 'Login',
        'register': 'Register',
        'logout': 'Logout',
        'profile': 'Account',
        'admin': 'Admin',
        'wishlist': 'Wishlist',
        'compare': 'Compare',
        'notifications': 'Notifications',

        // Homepage
        'flash_sale': 'Flash Sale',
        'top_search': 'Top Search',
        'categories': 'Categories',
        'suggestions': "Today's Picks",
        'view_all': 'View all',
        'buy_now': 'Buy now',
        'add_to_cart': 'Add to cart',
        'sold': 'Sold',

        // Product
        'product_detail': 'Product Detail',
        'description': 'Description',
        'reviews': 'Reviews',
        'size_guide': 'Size Guide',
        'similar_products': 'Similar Products',
        'you_may_like': 'You may also like',
        'write_review': 'Write a review',
        'rating': 'Rating',
        'comment': 'Comment',
        'submit_review': 'Submit review',

        // Cart & Checkout
        'your_cart': 'Your Cart',
        'checkout': 'Checkout',
        'total': 'Total',
        'shipping_info': 'Shipping Information',
        'payment_method': 'Payment Method',
        'cod': 'Cash on Delivery',
        'bank_transfer': 'Bank Transfer',
        'e_wallet': 'E-Wallet',
        'place_order': 'Place Order',
        'order_success': 'Order placed successfully!',
        'discount_code': 'Discount Code',
        'apply': 'Apply',

        // Orders
        'my_orders': 'My Orders',
        'order_tracking': 'Order Tracking',
        'processing': 'Processing',
        'shipping': 'Shipping',
        'delivered': 'Delivered',
        'cancelled': 'Cancelled',
        'cancel_order': 'Cancel Order',
        'order_detail': 'Order Detail',

        // Profile
        'my_profile': 'My Profile',
        'full_name': 'Full Name',
        'phone': 'Phone',
        'address': 'Address',
        'city': 'City/Province',
        'district': 'District',
        'ward': 'Ward',
        'save': 'Save',
        'edit': 'Edit',

        // Chat
        'chat_support': 'Live Support',
        'chat_greeting': 'Hello! How can I help you?',
        'type_message': 'Type a message...',
        'send': 'Send',

        // Virtual Try-On
        'virtual_tryon': 'Virtual Try-On 3D',
        'height': 'Height',
        'weight': 'Weight',
        'fit_score': 'Fit Score',

        // Footer
        'newsletter': 'Subscribe',
        'newsletter_desc': 'Sign up to receive discount codes and latest offers',
        'subscribe': 'Subscribe',
        'about_us': 'About Us',
        'help_center': 'Help Center',
        'policies': 'Policies',

        // General
        'loading': 'Loading...',
        'error': 'An error occurred',
        'success': 'Success',
        'confirm': 'Confirm',
        'cancel': 'Cancel',
        'close': 'Close',
        'back': 'Go back',
        'no_results': 'No results found',
        'language': 'Language',
        'search_btn': 'Search',
        'customer_service': 'Customer Service',
        'about_shopee': 'About VFit',
        'connect_with_us': 'Connect with us:',
        'payment_methods_label': 'Payment methods:',
        'copyright': 'Copyright belongs to VFit.',
        'country_region': 'Country & Region:',
        'footer_desc': 'Vietnam\'s leading e-commerce platform, bringing a wonderful shopping experience with millions of quality products.',
        'help_center_link': 'Help Center',
        'buy_guide': 'Buying Guide',
        'sell_guide': 'Selling Guide',
        'payment_link': 'Payment',
        'shipping_link': 'Shipping',
        'return_policy': 'Return Policy',
        'intro_shopee': 'About VFit',
        'terms': 'Terms of Service',
        'privacy_policy': 'Privacy Policy',
        'cookie_policy': 'Cookie Policy',

        // FlashSale
        'ends_in': 'Ends in:',
        'view_all_flash': 'View All Flash Sales',
        'in_stock': 'Left',

        // Category
        'fashion_categories': 'FASHION CATEGORIES',

        // ProductList
        'no_products': 'No products found',
        'remove_wishlist': 'Remove from wishlist',
        'add_wishlist': 'Add to wishlist',
        'quick_view': 'Quick view',
        'view_product': 'View product',

        // CartModal
        'empty_cart': 'Your cart is empty.',
        'select_all': 'Select all',
        'quantity_label': 'Quantity:',
        'delete': 'Delete',
        'total_payment': 'Total Payment',
        'buy_items': 'Purchase',
        'select_item_warning': 'Please select at least one product!',
        'products_unit': 'products',

        // ProductDetail
        'color_label': 'Color',
        'size_label': 'Size',
        'add_to_cart_btn': 'Add to Cart',
        'buy_now_btn': 'Buy Now',
        'try_3d_btn': 'Try on 3D Model',
        'product_specs': 'PRODUCT DETAILS',
        'category_label': 'Category',
        'material_label': 'Material',
        'material_value': 'Premium Denim, Cotton',
        'pattern_label': 'Pattern',
        'pattern_value': 'Solid / Patterned',
        'origin_label': 'Origin',
        'origin_value': 'Vietnam',
        'product_reviews_title': 'PRODUCT REVIEWS',
        'review_count_label': 'reviews',
        'all_filter': 'All',
        'star_label': 'Stars',
        'has_comments': 'With Comments',
        'has_images': 'With Images',
        'write_your_review': 'Write Your Review',
        'your_rating': 'Your rating',
        'your_comment': 'Your comment',
        'share_experience': 'Share your experience about this product...',
        'submit_review_btn': 'Submit Review',
        'login_to_review': 'Login required to review',
        'login_to_review_desc': 'Please login to share your experience about this product',
        'login_now': 'Login Now',
        'no_matching_reviews': 'No reviews match this filter',
        'view_more_reviews': 'View More Reviews',
        'classification': 'Type:',
        'shop_reply': 'Shop Reply:',
        'product_not_found': 'Product not found',
        'please_login_review': 'Please login to review',
        'please_enter_review': 'Please enter review content',
        'review_submitted': 'Your review has been submitted!',
        'need_login_buy': 'Please login to purchase!',
        'please_select_size': 'Please select a size!',
        'fashion_breadcrumb': 'Fashion',
        'not_selected': 'Not selected',
        'user_default': 'User',

        // Checkout
        'standard_shipping': 'Standard Shipping',
        'express_shipping': 'Express Shipping',
        'super_shipping': 'Super Fast Shipping',
        'standard_time': '3-5 days',
        'express_time': '1-2 days',
        'super_time': 'Same day',
        'today_text': 'Today',
        'selected_products': 'Selected Products',
        'product_col': 'Product',
        'unit_price': 'Unit Price',
        'quantity_col': 'Quantity',
        'total_col': 'Total',
        'shipping_method_label': 'Shipping Method',
        'shipping_hint': 'Choose a shipping method that suits you',
        'expected_label': 'Expected',
        'payment_title': 'Payment',
        'subtotal': 'Subtotal:',
        'shipping_fee_label': 'Shipping fee:',
        'expected_delivery': 'Expected delivery:',
        'discount_code_label': 'Discount Code',
        'enter_discount': 'Enter discount code',
        'receiver_info': 'Receiver Information',
        'full_name_star': 'Full name *',
        'phone_star': 'Phone *',
        'address_star': 'Address *',
        'address_hint': 'To change address, please update in',
        'your_profile_link': 'your Profile',
        'ward_star': 'Ward *',
        'district_star': 'District *',
        'city_star': 'City/Province *',
        'cod_full': 'Cash on Delivery (COD)',
        'banking_full': 'Bank Transfer',
        'online_full': 'Online Payment (MoMo, ZaloPay, VNPAY...)',
        'security_title': 'Information Security:',
        'security_desc': 'Your information is encrypted and absolutely secure. We are committed to not sharing personal data with third parties.',
        'processing_order': 'Processing...',
        'place_order_now': 'Place Order Now',
        'confirm_order_title': 'Confirm Order',
        'confirm_check_info': 'Please review your order information:',
        'confirm_order_btn': 'Confirm Order',
        'cart_step': '1. Cart',
        'shipping_step': '2. Shipping',
        'payment_step': '3. Payment',
        'no_products_selected': 'No products selected',
        'select_products_hint': 'Please select products for checkout!',
        'select_products_btn': 'SELECT PRODUCTS',
        'no_product_found': 'No products found!',
        'please_select_products': 'Please select products first!',
        'please_login_checkout': 'Please login to checkout!',
        'update_address_warning': 'Please update your shipping address in your Profile!',
        'update_full_info': 'Please update complete shipping info in your Profile!',
        'no_products_warning': 'No products selected!',
        'please_login_again': 'Please login again!',
        'order_failed': 'Order placement failed!',
        'used_all_coupons': 'You have used all discount codes',
        'coupon_from_newsletter': 'Newsletter subscription code',
        'discount_code_text': 'Discount code',
        'select_btn': 'Select',
        'hide_btn': 'Hide',
        'codes_count': 'codes',
        'enter_discount_error': 'Please enter a discount code',
        'coupon_invalid': 'Invalid discount code',
        'please_login_coupon': 'Please login to use discount code',
        'cannot_check_coupon': 'Cannot verify discount code. Please try again',
        'coupon_already_used': 'You have already used this discount code',
        'coupon_check_error': 'Error checking discount code. Please try again',

        // UserProfile
        'personal_info': 'Personal Information',
        'my_orders_tab': 'My Orders',
        'select_city': '-- Select City/Province --',
        'select_district': '-- Select District --',
        'select_ward': '-- Select Ward --',
        'street_address': 'House number, Street',
        'street_placeholder': 'e.g.: 123, ABC Street',
        'view_on_map': 'View on map',
        'save_info': 'Save information',
        'loading_orders': 'Loading orders...',
        'no_orders_yet': 'You have no orders yet',
        'shop_now': 'Shop Now',
        'order_label': 'Order:',
        'total_amount_label': 'Total:',
        'shipping_info_title': 'Shipping Information',
        'reorder_btn': 'Reorder',
        'delete_order_btn': 'Delete Order',
        'confirm_cancel': 'Are you sure you want to cancel this order?',
        'confirm_delete': 'Are you sure you want to delete this order?',
        'cancel_success': 'Order cancelled successfully',
        'delete_success': 'Order deleted successfully',
        'added_to_cart_msg': 'Products added to cart!',
        'cannot_load_orders': 'Cannot load orders',
        'please_login_page': 'Please login to view this page!',

        // TopSearch
        'top_search_title': 'TOP SEARCH',
        'sold_count_monthly': 'Sold',
        'monthly_suffix': '/ month',

        // ReviewCarousel
        'customer_reviews_title': '💬 What Our Customers Say',
        'customer_reviews_subtitle': 'Over 100,000+ happy customers',
        'review_product_label': 'Product:',

        // BrandPartners
        'brand_partners_title': '🤝 Brand Partners',
        'brand_partners_subtitle': 'Partnered with world-leading brands',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('language');
        if (saved && (saved === 'vi' || saved === 'en')) return saved;
        // Auto-detect từ browser
        const browserLang = navigator.language || navigator.userLanguage;
        return browserLang.startsWith('vi') ? 'vi' : 'en';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.lang = language;
    }, [language]);

    const t = (key) => {
        return translations[language]?.[key] || translations['vi']?.[key] || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'vi' ? 'en' : 'vi');
    };

    const value = {
        language,
        setLanguage,
        toggleLanguage,
        t,
        isVietnamese: language === 'vi',
        isEnglish: language === 'en',
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};
